(cl:in-package hw2stats-msg)
(cl:export '(HEADER-VAL
          HEADER
          PASSCOMPLEATIONPERCENTAGE-VAL
          PASSCOMPLEATIONPERCENTAGE
          PASSINCOMPLETIONPERCENTAGE-VAL
          PASSINCOMPLETIONPERCENTAGE
          TOTALRUSHINGYARDS-VAL
          TOTALRUSHINGYARDS
          TOTALPASSINGYARDS-VAL
          TOTALPASSINGYARDS
))