(cl:in-package hw2stats-msg)
(cl:export '(HEADER-VAL
          HEADER
          TOTALPASSESCOMPLEATED-VAL
          TOTALPASSESCOMPLEATED
          TOTALPASSESDROPPED-VAL
          TOTALPASSESDROPPED
          TOTALRUSHINGYARDS-VAL
          TOTALRUSHINGYARDS
          TOTALPASSINGYARDS-VAL
          TOTALPASSINGYARDS
))