// Generated by gencpp from file hw2stats/offensivePlay.msg
// DO NOT EDIT!


#ifndef HW2STATS_MESSAGE_OFFENSIVEPLAY_H
#define HW2STATS_MESSAGE_OFFENSIVEPLAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hw2stats
{
template <class ContainerAllocator>
struct offensivePlay_
{
  typedef offensivePlay_<ContainerAllocator> Type;

  offensivePlay_()
    : header()
    , isPass(false)
    , passCompleted(false)
    , yards(0)
    , touchdown(false)  {
    }
  offensivePlay_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isPass(false)
    , passCompleted(false)
    , yards(0)
    , touchdown(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isPass_type;
  _isPass_type isPass;

   typedef uint8_t _passCompleted_type;
  _passCompleted_type passCompleted;

   typedef int32_t _yards_type;
  _yards_type yards;

   typedef uint8_t _touchdown_type;
  _touchdown_type touchdown;





  typedef boost::shared_ptr< ::hw2stats::offensivePlay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw2stats::offensivePlay_<ContainerAllocator> const> ConstPtr;

}; // struct offensivePlay_

typedef ::hw2stats::offensivePlay_<std::allocator<void> > offensivePlay;

typedef boost::shared_ptr< ::hw2stats::offensivePlay > offensivePlayPtr;
typedef boost::shared_ptr< ::hw2stats::offensivePlay const> offensivePlayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw2stats::offensivePlay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw2stats::offensivePlay_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw2stats::offensivePlay_<ContainerAllocator1> & lhs, const ::hw2stats::offensivePlay_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isPass == rhs.isPass &&
    lhs.passCompleted == rhs.passCompleted &&
    lhs.yards == rhs.yards &&
    lhs.touchdown == rhs.touchdown;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw2stats::offensivePlay_<ContainerAllocator1> & lhs, const ::hw2stats::offensivePlay_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw2stats

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw2stats::offensivePlay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw2stats::offensivePlay_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2stats::offensivePlay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2stats::offensivePlay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2stats::offensivePlay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2stats::offensivePlay_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw2stats::offensivePlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cc2e5218b4d02ce6aef8b26affe7470";
  }

  static const char* value(const ::hw2stats::offensivePlay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cc2e5218b4d02ceULL;
  static const uint64_t static_value2 = 0x6aef8b26affe7470ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw2stats::offensivePlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw2stats/offensivePlay";
  }

  static const char* value(const ::hw2stats::offensivePlay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw2stats::offensivePlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# true if the play was a pass, else it was a run\n"
"bool isPass\n"
"# if this was a pass, true if it was completed\n"
"bool passCompleted\n"
"# number of yards gained/lost from the play\n"
"int32 yards\n"
"# true if this play resulted in a touchdown\n"
"bool touchdown\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hw2stats::offensivePlay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw2stats::offensivePlay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isPass);
      stream.next(m.passCompleted);
      stream.next(m.yards);
      stream.next(m.touchdown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct offensivePlay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw2stats::offensivePlay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw2stats::offensivePlay_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isPass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPass);
    s << indent << "passCompleted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.passCompleted);
    s << indent << "yards: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yards);
    s << indent << "touchdown: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.touchdown);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW2STATS_MESSAGE_OFFENSIVEPLAY_H
