// Generated by gencpp from file hw2stats/rocketState.msg
// DO NOT EDIT!


#ifndef HW2STATS_MESSAGE_ROCKETSTATE_H
#define HW2STATS_MESSAGE_ROCKETSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hw2stats
{
template <class ContainerAllocator>
struct rocketState_
{
  typedef rocketState_<ContainerAllocator> Type;

  rocketState_()
    : header()
    , altitude(0.0)
    , velocity(0.0)
    , acceleration(0.0)  {
    }
  rocketState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude(0.0)
    , velocity(0.0)
    , acceleration(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::hw2stats::rocketState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw2stats::rocketState_<ContainerAllocator> const> ConstPtr;

}; // struct rocketState_

typedef ::hw2stats::rocketState_<std::allocator<void> > rocketState;

typedef boost::shared_ptr< ::hw2stats::rocketState > rocketStatePtr;
typedef boost::shared_ptr< ::hw2stats::rocketState const> rocketStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw2stats::rocketState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw2stats::rocketState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw2stats::rocketState_<ContainerAllocator1> & lhs, const ::hw2stats::rocketState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.altitude == rhs.altitude &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw2stats::rocketState_<ContainerAllocator1> & lhs, const ::hw2stats::rocketState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw2stats

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hw2stats::rocketState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw2stats::rocketState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2stats::rocketState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw2stats::rocketState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2stats::rocketState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw2stats::rocketState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw2stats::rocketState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12b6a599c963c632ced2ca8b896ee600";
  }

  static const char* value(const ::hw2stats::rocketState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12b6a599c963c632ULL;
  static const uint64_t static_value2 = 0xced2ca8b896ee600ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw2stats::rocketState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw2stats/rocketState";
  }

  static const char* value(const ::hw2stats::rocketState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw2stats::rocketState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Rocket position\n"
"float64 altitude\n"
"# Tocket velocity\n"
"float64 velocity\n"
"# Rocket acceleration\n"
"float64 acceleration\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hw2stats::rocketState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw2stats::rocketState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude);
      stream.next(m.velocity);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rocketState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw2stats::rocketState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw2stats::rocketState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW2STATS_MESSAGE_ROCKETSTATE_H
