(cl:in-package balboa_core-msg)
(cl:export '(HEADER-VAL
          HEADER
          ARDUINOMILLIS-VAL
          ARDUINOMILLIS
          BATTERYMILLIVOLTS-VAL
          BATTERYMILLIVOLTS
          ANGLEY-VAL
          ANGLEY
          ANGLEX-VAL
          ANGLEX
          ANGLEZ-VAL
          ANGLEZ
          DRIVELEFT-VAL
          DRIVELEFT
          DRIVERIGHT-VAL
          DRIVERIGHT
          SPEEDLEFT-VAL
          SPEEDLEFT
          SPEEDRIGHT-VAL
          SPEEDRIGHT
          DISTANCELEFT-VAL
          DISTANCELEFT
          DISTANCERIGHT-VAL
          DISTANCERIGHT
          IRSENSOR1-VAL
          IRSENSOR1
          IRSENSOR2-VAL
          IRSENSOR2
          IRSENSOR3-VAL
          IRSENSOR3
          IRSENSOR4-VAL
          IRSENSOR4
          IRSENSOR5-VAL
          IRSENSOR5
          RANGESENSOR-VAL
          RANGESENSOR
))