// Generated by gencpp from file balboa_controller/irArray.msg
// DO NOT EDIT!


#ifndef BALBOA_CONTROLLER_MESSAGE_IRARRAY_H
#define BALBOA_CONTROLLER_MESSAGE_IRARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace balboa_controller
{
template <class ContainerAllocator>
struct irArray_
{
  typedef irArray_<ContainerAllocator> Type;

  irArray_()
    : header()
    , sensor1(0)
    , sensor2(0)
    , sensor4(0)
    , sensor5(0)  {
    }
  irArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor1(0)
    , sensor2(0)
    , sensor4(0)
    , sensor5(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _sensor1_type;
  _sensor1_type sensor1;

   typedef int8_t _sensor2_type;
  _sensor2_type sensor2;

   typedef int8_t _sensor4_type;
  _sensor4_type sensor4;

   typedef int8_t _sensor5_type;
  _sensor5_type sensor5;





  typedef boost::shared_ptr< ::balboa_controller::irArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balboa_controller::irArray_<ContainerAllocator> const> ConstPtr;

}; // struct irArray_

typedef ::balboa_controller::irArray_<std::allocator<void> > irArray;

typedef boost::shared_ptr< ::balboa_controller::irArray > irArrayPtr;
typedef boost::shared_ptr< ::balboa_controller::irArray const> irArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balboa_controller::irArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balboa_controller::irArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::balboa_controller::irArray_<ContainerAllocator1> & lhs, const ::balboa_controller::irArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor1 == rhs.sensor1 &&
    lhs.sensor2 == rhs.sensor2 &&
    lhs.sensor4 == rhs.sensor4 &&
    lhs.sensor5 == rhs.sensor5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::balboa_controller::irArray_<ContainerAllocator1> & lhs, const ::balboa_controller::irArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace balboa_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::balboa_controller::irArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balboa_controller::irArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balboa_controller::irArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balboa_controller::irArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balboa_controller::irArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balboa_controller::irArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balboa_controller::irArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71fa43eb942c785a9beda432cf89109d";
  }

  static const char* value(const ::balboa_controller::irArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71fa43eb942c785aULL;
  static const uint64_t static_value2 = 0x9beda432cf89109dULL;
};

template<class ContainerAllocator>
struct DataType< ::balboa_controller::irArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balboa_controller/irArray";
  }

  static const char* value(const ::balboa_controller::irArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balboa_controller::irArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 sensor1\n"
"int8 sensor2\n"
"int8 sensor4\n"
"int8 sensor5\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::balboa_controller::irArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balboa_controller::irArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor1);
      stream.next(m.sensor2);
      stream.next(m.sensor4);
      stream.next(m.sensor5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct irArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balboa_controller::irArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balboa_controller::irArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor1);
    s << indent << "sensor2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor2);
    s << indent << "sensor4: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor4);
    s << indent << "sensor5: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALBOA_CONTROLLER_MESSAGE_IRARRAY_H
